// GET MOVIE
export const GET_MOVIE                  = 'GET_MOVIE';
export const GET_MOVIE_SUCCESS          = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL             = 'GET_MOVIE_FAIL';

// GET MOVIE CREDITS
export const GET_MOVIE_CREDITS          = 'GET_MOVIE_CREDITS';
export const GET_MOVIE_CREDITS_SUCCESS  = 'GET_MOVIE_CREDITS_SUCCESS';
export const GET_MOVIE_CREDITS_FAIL     = 'GET_MOVIE_CREDITS_FAIL';

// GET MOVIE RATINGS
export const GET_MOVIE_RATINGS          = 'GET_MOVIE_RATINGS';
export const GET_MOVIE_RATINGS_SUCCESS  = 'GET_MOVIE_RATINGS_SUCCESS';
export const GET_MOVIE_RATINGS_FAIL     = 'GET_MOVIE_RATINGS_FAIL';

// GET MOVIE VIDEOS
export const GET_MOVIE_VIDEOS           = 'GET_MOVIE_VIDEOS';
export const GET_MOVIE_VIDEOS_SUCCESS   = 'GET_MOVIE_VIDEOS_SUCCESS';
export const GET_MOVIE_VIDEOS_FAIL      = 'GET_MOVIE_VIDEOS_FAIL';

// GET MOVIE VIDEOS
export const GET_MOVIE_SIMILAR          = 'GET_MOVIE_SIMILAR';
export const GET_MOVIE_SIMILAR_SUCCESS  = 'GET_MOVIE_SIMILAR_SUCCESS';
export const GET_MOVIE_SIMILAR_FAIL     = 'GET_MOVIE_SIMILAR_FAIL';

// GET POPULAR MOVIES
export const GET_POPULAR_MOVIE         = 'GET_POPULAR_MOVIE';
export const GET_POPULAR_MOVIE_SUCCESS = 'GET_POPULAR_MOVIE_SUCCESS';
export const GET_POPULAR_MOVIE_FAIL    = 'GET_POPULAR_MOVIE_FAIL';