// SEARCH
export const SEARCH = 'SEARCH_MOVIE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

// GET MOVIE
export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';

// GET MOVIE CREDITS
export const GET_MOVIE_CREDITS = 'GET_MOVIE_CREDITS';
export const GET_MOVIE_CREDITS_SUCCESS = 'GET_MOVIE_CREDITS_SUCCESS';
export const GET_MOVIE_CREDITS_FAIL = 'GET_MOVIE_CREDITS_FAIL';

// GET MOVIE RATINGS
export const GET_MOVIE_RATINGS = 'GET_MOVIE_RATINGS';
export const GET_MOVIE_RATINGS_SUCCESS = 'GET_MOVIE_RATINGS_SUCCESS';
export const GET_MOVIE_RATINGS_FAIL = 'GET_MOVIE_RATINGS_FAIL';

// GET MOVIE VIDEOS
export const GET_MOVIE_VIDEOS = 'GET_MOVIE_VIDEOS';
export const GET_MOVIE_VIDEOS_SUCCESS = 'GET_MOVIE_VIDEOS_SUCCESS';
export const GET_MOVIE_VIDEOS_FAIL = 'GET_MOVIE_VIDEOS_FAIL';

// GET MOVIE VIDEOS
export const GET_MOVIE_SIMILAR = 'GET_MOVIE_SIMILAR';
export const GET_MOVIE_SIMILAR_SUCCESS = 'GET_MOVIE_SIMILAR_SUCCESS';
export const GET_MOVIE_SIMILAR_FAIL = 'GET_MOVIE_SIMILAR_FAIL';

// GET POPULAR MOVIES
export const GET_POPULAR_MOVIE = 'GET_POPULAR_MOVIE';
export const GET_POPULAR_MOVIE_SUCCESS = 'GET_POPULAR_MOVIE_SUCCESS';
export const GET_POPULAR_MOVIE_FAIL = 'GET_POPULAR_MOVIE_FAIL';

// GET UPCOMING MOVIES
export const GET_UPCOMING_MOVIE = 'GET_UPCOMING_MOVIE_MOVIE';
export const GET_UPCOMING_MOVIE_SUCCESS = 'GET_UPCOMING_MOVIE_SUCCESS';
export const GET_UPCOMING_MOVIE_FAIL = 'GET_UPCOMING_MOVIE_FAIL';

// GET NOW PLAYING MOVIES
export const GET_NOW_PLAYING_MOVIE = 'GET_NOW_PLAYING_MOVIE';
export const GET_NOW_PLAYING_MOVIE_SUCCESS = 'GET_NOW_PLAYING_MOVIE_SUCCESS';
export const GET_NOW_PLAYING_MOVIE_FAIL = 'GET_NOW_PLAYING_MOVIE_FAIL';

// GET PERSON
export const GET_PERSON = 'GET_PERSON_MOVIE';
export const GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS';
export const GET_PERSON_FAIL = 'GET_PERSON_FAIL';

// GET PERSON CREDITS
export const GET_PERSON_CREDITS = 'GET_PERSON_CREDITS';
export const GET_PERSON_CREDITS_SUCCESS = 'GET_PERSON_CREDITS_SUCCESS';
export const GET_PERSON_CREDITS_FAIL = 'GET_PERSON_CREDITS_FAIL';

// GET PERSON IMAGES
export const GET_PERSON_IMAGES = 'GET_PERSON_IMAGES';
export const GET_PERSON_IMAGES_SUCCESS = 'GET_PERSON_IMAGES_SUCCESS';
export const GET_PERSON_IMAGES_FAIL = 'GET_PERSON_IMAGES_FAIL';
