// SEARCH
export const SEARCH_REQUEST = 'SEARCH_MOVIE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

// SEARCH MODAL
export const SHOW_SEARCH_MODAL = 'SHOW_SEARCH_MODAL';
export const HIDE_SEARCH_MODAL = 'HIDE_SEARCH_MODAL';

// FETCH MOVIE
export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE';

// FETCH HOMEPAGE
export const FETCH_HOMPAGE_REQUEST = 'FETCH_HOMPAGE_REQUEST';
export const FETCH_HOMPAGE_SUCCESS = 'FETCH_HOMPAGE_SUCCESS';
export const FETCH_HOMPAGE_FAILURE = 'FETCH_HOMPAGE_FAILURE';

// FETCH PERSON
export const FETCH_PERSON_REQUEST = 'FETCH_PERSON_REQUEST';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILURE = 'FETCH_PERSON_FAILURE';
